version: '3'
services:
  decidim:
    env_file:
      - .env
    build: .
    #image: decidim/decidim:${DECIDIM_VERSION}
    command: /bin/bash -c "/code/bin/rails db:create db:migrate db:seed; /code/bin/rails server -b 0.0.0.0"
    stdin_open: true
    tty: true
    #working_dir: "/code"
    ports:
      - "${PUBLIC_PORT}:3000"
    volumes:
      - code:/code
    links:
      - pg
      - redis
  pg:
    image: postgres
    env_file:
      - .env
    #ports:
    #  - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  code: {}     
  pg-data: {}
  redis-data: {}
